src/features/channels/components/channel-list/create-channel/CreateButton.styles.ts
small fix on the button so it is aligned to the box in its right
=> Button is aligned to the right

src/features/channels/components/channel-list/search-channel/SearchChannel.tsx
=> feat: hidden channels displayed

src/features/channels/components/channel-list/search-channel/SearchChannel.tsx, src/features/channels/components/chat-header/ChatHeader.tsx, src/features/channels/components/message-input/MessageInput.tsx
commented out some buttons but will come back in later sprints
=> feat: commented out buttons that are not working

package.json, src/features/channels/components/channel-list/create-channel/CreateButton.tsx, tsconfig.json, yarn.lock
the user cannot enter emoji as a first letter.
=> feat: disabled emoji as a first letter

src/features/channels/components/chat-header/ChatHeader.tsx
The bug image is not present anymore.
=> feat: replace bug imge into 1st letter as avatar

src/common/router/suspense-loader/SuspenseLoader.styles.ts, yarn.lock
Spinner in the middle of the text input field.
=> feat: fixed the loader's place

src/features/channels/components/chat-content/message/Message.styles.ts, src/features/channels/components/chat-content/message/Message.tsx
Now the user's ID is shortened but still you can copy paste the entire ID, eventually this will be a user's name.
=> feat: made a user name short so it doesn't overlap

src/features/channels/components/message-input/MessageInput.styles.ts
It is 1rem left and right.  1rem top and bottom.
=> feat: added padding of 1rem instead of 0.5rem

src/features/channels/components/chat-content/message/Message.styles.ts
changed color to a dark green instead of blue.
=> feat: changed color of message background

src/features/channels/components/chat-content/message/Message.styles.ts, src/layout/Main.tsx
left padding on right grid is 0 px now
=> feat: deleted the left padding on right Grid

src/features/channels/components/channel-list/wallet/Wallet.tsx, src/features/channels/components/channel-list/wallet/receive-jup/receive-jup.styles.ts, src/features/channels/components/channel-list/wallet/receive-jup/receive-jup.tsx, src/features/invites/components/InvitesList/InvitesList.tsx
Improvements for Wallet's layout/UI
=> Bug/transaction UI

src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.styles.ts, src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.tsx, src/features/channels/components/channel-list/search-channel/SearchChannel.styles.ts, src/features/channels/components/channel-list/search-channel/SearchChannel.tsx
Added the camera icon only when on hover.
=> Upload pics

src/features/channels/components/chat-header/channel-info/ChannelInfo.tsx, yarn.lock
Now you can see the channel members in real time
=> fix: channel info update real time

src/features/channels/components/invite-user-modal/InviteUserModal.tsx
When sending an invitation, the modal closes.
Ready for review.
=> fix: modal update when invitation is sent

src/features/channels/components/channel-list/create-channel/CreateButton.styles.ts, src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.tsx, src/features/channels/components/message-input/MessageInput.tsx, src/features/invites/components/InvitesList/InvitesList.tsx
Fix position icon to send attachment and channel invite counter.
Ready for review.
=> fix: position icon to send attachment and channel invite counter

src/pages/login-page/LoginPage.styles.ts, src/pages/login-page/LoginPage.tsx
=> fix: status request sync device

src/features/channels/components/channel-list/about/about.tsx, src/features/channels/components/chat-content/message/Message.tsx, src/features/channels/components/chat-header/channel-info/ChannelInfo.styles.ts, src/features/channels/components/chat-header/channel-info/ChannelInfo.tsx
=> fix: wrong consistency in code

src/features/channels/components/message-input/MessageInput.styles.ts, src/features/channels/components/message-input/MessageInput.tsx
=> fix: input type message

src/common/components/ui/spinner/Spinner.styles.ts, src/features/auth/store/auth.actions.ts, src/features/auth/store/auth.slice.spec.ts, src/features/auth/store/auth.slice.ts, src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.tsx, src/features/channels/components/channel-list/search-channel/SearchChannel.tsx, src/features/channels/hooks/useUploadImageProfile.ts, src/features/channels/store/channel.actions.ts, src/features/channels/store/channel.slice.ts
=> refactor: image profile

src/pages/login-page/LoginPage.styles.ts, src/pages/login-page/LoginPage.tsx
added glow effect and made it easy to see the account selected.
=> Account design

src/features/auth/components/SignInButton/SignInButton.tsx, src/features/auth/components/SyncAccount/SyncAccount.tsx
=> fix: changed words so it's easy to understand

src/common/components/ui/Modal/index.tsx, src/features/auth/components/SyncAccount/SyncAccount.styles.ts, src/features/auth/components/SyncAccount/SyncAccount.tsx
added glow effect to the buttons, made the background darker when asking for permission.
=> Fix colors UI

src/features/channels/components/chat-content/ChatContent.tsx, src/features/channels/components/chat-content/message/Message.tsx, src/features/channels/components/chat-header/ChatHeader.tsx, src/features/channels/components/chat-header/channel-info/ChannelInfo.tsx, src/features/channels/components/invite-user-modal/InviteUserModal.tsx, src/features/channels/store/channel.actions.ts, src/features/channels/types/members.interface.ts, src/features/invites/components/InvitesList/InvitesList.tsx
=> refactor: profile picture in channel messages

src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.styles.ts, src/features/channels/components/channel-list/profile-avatar/ProfileAvatar.tsx
=> feat: added alias to the drawer

src/features/channels/components/channel-list/channel-list-item/ChannelListItem.styles.ts, src/features/channels/components/channel-list/channel-list-item/ChannelListItem.tsx, src/features/channels/components/channel-list/modal-hidden-list/ModalHiddenList.styles.ts, src/features/channels/components/chat-content/ChatContent.tsx, src/features/channels/components/chat-content/message-reply/MessageReply.styles.ts, src/features/channels/components/chat-header/ChatHeader.styles.ts, src/features/channels/components/chat-header/ChatHeader.tsx, src/layout/Main.styles.ts, src/layout/Main.tsx, src/layout/sections/HeaderSection.tsx, src/layout/sections/Section.styles.ts
changed the main parts, we need to work on the details in the future.
=> feat: changed sizes, and layout when shrunk

src/features/channels/components/channel-list/ChannelList.styles.ts, src/features/channels/components/channel-list/search-channel/SearchChannel.tsx, src/layout/sections/HeaderSection.tsx, src/layout/sections/Section.styles.ts
=> Copyburger

src/features/channels/components/channel-list/wallet/receive-jup/receive-jup.styles.ts, src/features/channels/components/channel-list/wallet/send-jup/send-jup.styles.ts, src/features/channels/components/channel-list/wallet/transactions/Transactions.styles.ts, src/features/channels/components/channel-list/wallet/transactions/Transactions.tsx
added ui modification to the wallet
=> Fix wallet design

src/features/channels/components/header-channel-list/search-channel/SearchChannel.tsx
=> Center search new

src/features/channels/components/message-input/MessageInput.tsx
=> Attachement styling

src/features/auth/components/Tutorial/Tutorial.styles.ts
Tutorial images alignment issue solved
=> fix: images alignment problem in tutorial

index.html, src/assets/images/misc/hamburger.svg, src/features/channels/components/channel-drawer/ChannelDrawer.styles.ts, src/features/channels/components/channel-drawer/ChannelDrawer.tsx, src/features/channels/components/header-channel-list/HeaderChannelList.styles.ts, src/features/channels/components/header-channel-list/HeaderChannelList.tsx, src/features/channels/components/header-channel-list/search-channel/SearchChannel.styles.ts, src/features/channels/components/header-channel-list/search-channel/SearchChannel.tsx
=> feat: channel header redesign

src/assets/images/misc/add-channel-btn.svg, src/features/auth/components/SignInButton/SignInButton.tsx, src/features/channels/components/channel-drawer/ChannelDrawer.styles.ts, src/features/channels/components/channel-list/ChannelList.tsx, src/features/channels/components/channel-list/channel-list-item/ChannelListItem.styles.ts, src/features/channels/components/channel-list/channel-list-item/ChannelListItem.tsx, src/features/channels/components/channel-list/create-channel/CreateChannel.styles.ts, src/features/channels/components/channel-list/create-channel/CreateChannel.tsx, src/features/channels/components/header-channel-list/HeaderChannelList.styles.ts, src/features/channels/components/header-channel-list/search-channel/SearchChannel.styles.ts, src/features/invites/components/InvitesList/InviteListItem/InviteListItem.tsx, src/features/invites/components/InvitesList/InvitesList.tsx, src/layout/Main.styles.ts, src/layout/Main.tsx, src/layout/sections/MainSection.tsx, src/layout/sections/Section.styles.ts, src/pages/login-page/LoginPage.styles.ts
HeaderWrapper, CreateChannel btn, SearchChannel, InvitesSenction, InvitesItems, redesinged and refactored.
=> feat: leftColummn redesinged

src/common/components/ui/TextInput/TextInput.styles.ts, src/common/components/ui/TextInput/TextInput.tsx, src/common/components/ui/spinner-container/SpinnerContainer.styles.ts, src/common/components/ui/spinner-container/SpinnerContainer.tsx, src/features/channels/components/channel-drawer/ChannelDrawer.styles.ts, src/features/channels/components/channel-drawer/ChannelDrawer.tsx, src/features/channels/components/channel-list/about/about.styles.ts, src/features/channels/components/channel-list/channel-list-item/ChannelListItem.styles.ts, src/features/channels/components/chat-content/ChatContent.styles.ts, src/features/channels/components/chat-content/ChatContent.tsx, src/features/channels/components/chat-content/message/Message.styles.ts, src/features/channels/components/chat-content/message/Message.tsx, src/features/channels/components/chat-header/channel-info/ChannelInfo.styles.ts, src/features/channels/components/chat-header/channel-info/ChannelInfo.tsx, src/features/channels/components/header-channel-list/search-channel/SearchChannel.styles.ts, src/features/channels/components/header-channel-list/search-channel/SearchChannel.tsx, src/features/channels/components/message-input/MessageInput.styles.ts, src/features/channels/components/message-input/MessageInput.tsx, src/layout/Main.styles.ts
completed chat styling, infoChannel redesing, improved about&terms and conditions btns in profileChannel
=> feat: completed chat, channel info

src/assets/images/misc/receiveJUPIcon.svg, src/assets/images/misc/sendJUPIcon.svg, src/assets/images/misc/transactionsIcon.svg, src/common/components/ui/spinner-container/SpinnerContainer.styles.ts, src/features/auth/components/SignUpButton/SignUpButton.tsx, src/features/channels/components/channel-list/create-channel/CreateChannel.styles.ts, src/features/channels/components/channel-list/create-channel/CreateChannel.tsx, src/features/channels/components/channel-list/wallet/Wallet.styles.ts, src/features/channels/components/channel-list/wallet/Wallet.tsx, src/features/channels/components/channel-list/wallet/receive-jup/receive-jup.styles.ts, src/features/channels/components/channel-list/wallet/receive-jup/receive-jup.tsx, src/features/channels/components/channel-list/wallet/send-jup/send-jup.styles.ts, src/features/channels/components/channel-list/wallet/send-jup/send-jup.tsx, src/features/channels/components/channel-list/wallet/transactions/Transactions.styles.ts, src/features/channels/components/channel-list/wallet/transactions/Transactions.tsx, src/features/channels/components/chat-header/channel-info/ChannelInfo.styles.ts, src/features/channels/components/invite-user-modal/InviteUserModal.styles.ts, src/features/channels/components/invite-user-modal/InviteUserModal.tsx
Styled wallet, invite user modal
=> feat: wallet styling and modal part1

src/common/components/ui/TextInput/TextInput.tsx, src/features/channels/components/channel-drawer/ChannelDrawer.styles.ts, src/features/channels/components/channel-drawer/ChannelDrawer.tsx, src/features/channels/components/header-channel-list/HeaderChannelList.styles.ts, src/features/channels/components/header-channel-list/search-channel/SearchChannel.styles.ts, src/features/channels/components/header-channel-list/search-channel/SearchChannel.tsx, src/features/channels/components/message-input/MessageInput.tsx, src/features/channels/components/pending-channels-list/PendingChannelsList.styles.ts, src/features/channels/components/pending-channels-list/PendingChannelsList.tsx, src/features/invites/components/InvitesList/InvitesList.styles.ts, src/features/invites/components/InvitesList/InvitesList.tsx
optimized responsive, added click effects, restyled hamburger btn and search bar
=> feat: added click effects, optimized responsive
